server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update # Optional: configure schema generation (e.g., validate, update, create, create-drop)
    show-sql: true # Optional: to show SQL queries in logs
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
        missing-topics-fatal: false
  config:
    import: configserver:http://localhost:8085


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health # Expose specific endpoints
  endpoint:
    health:
      show-details: always  # Show details of health checks (e.g., database status)
#  health:
#    db:
#      enabled: true # Enable database health check
#  metrics:
#    enabled: true # Enable metrics
#  server:
#    port: 8081  # Optional: Expose actuator on a different port


resilience4j:
  circuitbreaker:
    instances:
      hotelRatingBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000 # in milliseconds
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      hotelRatingRetry:
        maxAttempts: 3
        waitDuration: 5000



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
