spring:
  application:
    name: HOTEL-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://user1:root@admincluster.nqkvy.mongodb.net/?retryWrites=true&w=majority&appName=AdminCluster
      database: rating_db
  config:
    import: configserver:http://localhost:8085

server:
  port: 8083

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka


